### ISSUE TITLE
Unhandled exception in script on Windows

### ISSUE THREAD

**Issue by jansendotsh** [iwalton3/plex-mpv-shim#102]
Howdy 👋 I was running this on Windows, installing the binary. It was working til a recent system update and now I'm getting the following `Unhandled exception in script`:

```
Traceback (most recent call last):
  File "run.py", line 21, in <module>
  File "plex_mpv_shim\mpv_shim.py", line 47, in main
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "plex_mpv_shim\player.py", line 606, in <module>
  File "plex_mpv_shim\player.py", line 113, in __init__
  File "python_mpv_jsonipc.py", line 421, in __init__
  File "python_mpv_jsonipc.py", line 227, in __init__
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by iwalton3** [comment]
Are you using the special external MPV mode? (If you don't know what this is, it is unlikely you are.)

**Comment by jansendotsh** [comment]
You caught the issue spot on. Looks like something happened that caused the config file to implode the shim. In any case, nothing wrong on the shim's side, just my config. I rolled it all back and it's working so I'll fuzz around a bit and see if I can define an external path with some arguments included for opening on a separate monitor. 

Sorry for the superfluous error report!
