### ISSUE TITLE
Unable to start plex-mpv-shim

### ISSUE THREAD

**Issue by jul-source** [iwalton3/plex-mpv-shim#11]
In a Ubuntu 18.04.4 fresh install after the installatiion following the official guide, the command plex-mpv-shim launch this:

2020-03-30 19:31:00,766 [    INFO] conf: Loaded settings from json: /home/julio/.config/plex-mpv-shim/conf.json
2020-03-30 19:31:00,882 [ WARNING] root: Cannot load GUI. Falling back to command line interface.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/plex_mpv_shim/mpv_shim.py", line 39, in main
    from .gui_mgr import userInterface
  File "/usr/local/lib/python3.6/dist-packages/plex_mpv_shim/gui_mgr.py", line 4, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
2020-03-30 19:31:00,998 [ WARNING] player: Could not find libmpv1.
2020-03-30 19:31:01,000 [    INFO] player: Using external mpv playback backend.
2020-03-30 19:31:01,001 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2020-03-30 19:31:01,001 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv185544798664445 for MPV.
2020-03-30 19:31:01,307 [   DEBUG] mpv-jsonipc: Found MPV socket.
2020-03-30 19:31:01,313 [ WARNING] mpv-jsonipc: Using fallback command list.
Traceback (most recent call last):
  File "/usr/local/bin/plex-mpv-shim", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/plex_mpv_shim/mpv_shim.py", line 47, in main
    from .player import playerManager
  File "/usr/local/lib/python3.6/dist-packages/plex_mpv_shim/player.py", line 499, in <module>
    playerManager = PlayerManager()
  File "/usr/local/lib/python3.6/dist-packages/plex_mpv_shim/player.py", line 100, in __init__
    self.menu = OSDMenu(self)
  File "/usr/local/lib/python3.6/dist-packages/plex_mpv_shim/menu.py", line 52, in __init__
    self.original_osd_color = playerManager._player.osd_back_color
  File "/usr/local/lib/python3.6/dist-packages/python_mpv_jsonipc.py", line 586, in __getattr__
    return self.command("get_property", name.replace("_", "-"))
  File "/usr/local/lib/python3.6/dist-packages/python_mpv_jsonipc.py", line 582, in command
    return self.mpv_inter.command(command, *args)
  File "/usr/local/lib/python3.6/dist-packages/python_mpv_jsonipc.py", line 306, in command
    raise MPVError(data["error"])
python_mpv_jsonipc.MPVError: error accessing property

**Comment by iwalton3** [comment]
It looks like you might have a problem with MPV, as it cannot talk to it. Try running the following:
```bash
sudo apt install libmpv1
```
If that doesn't work, you can try building MPV from source. Run the following:
```bash
sudo apt install autoconf automake libtool libharfbuzz-dev libfreetype6-dev libfontconfig1-dev libx11-dev libxrandr-dev libvdpau-dev libva-dev mesa-common-dev libegl1-mesa-dev yasm libasound2-dev libpulse-dev libuchardet-dev zlib1g-dev libfribidi-dev git libgnutls28-dev libgl1-mesa-dev libsdl2-dev cmake wget python g++ libluajit-5.1-dev
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build
echo --enable-libmpv-shared > mpv_options
./rebuild -j4
sudo ./install
sudo ldconfig
```

**Comment by jul-source** [comment]
Thank you. The libmpv1 doesn't resolve the issue. I'll try build MPV when I have some spare time.

**Comment by jul-source** [comment]
The MPV version 0.32 in the ppa:mc3man repository solves the issue.
Thank you
