### ISSUE TITLE
[BUG] TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Generator** [iwalton3/plex-mpv-shim#2]
On Archlinux from virtualenv

```
$ bin/plex-mpv-shim  
2019-08-19 15:11:14,147 [    INFO] Started GDM service
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aj/Desktop/plex-mpv-shim/lib/python3.7/site-packages/plex_mpv_shim/gdm.py", line 288, in run_discovery_loop
    self.discover()
  File "/home/aj/Desktop/plex-mpv-shim/lib/python3.7/site-packages/plex_mpv_shim/gdm.py", line 224, in discover
    if "200 OK" in response.get('data'):
TypeError: a bytes-like object is required, not 'str'

Traceback (most recent call last):
  File "bin/plex-mpv-shim", line 10, in <module>
    sys.exit(main())
  File "/home/aj/Desktop/plex-mpv-shim/lib/python3.7/site-packages/plex_mpv_shim/mpv_shim.py", line 48, in main
    gdm.discover()
  File "/home/aj/Desktop/plex-mpv-shim/lib/python3.7/site-packages/plex_mpv_shim/gdm.py", line 224, in discover
    if "200 OK" in response.get('data'):
TypeError: a bytes-like object is required, not 'str'
^CException ignored in: <module 'threading' from '/usr/lib64/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 1308, in _shutdown
    lock.acquire()
KeyboardInterrupt
```
**Info:**
Python 3.7.4
virtualenv3 16.1.0

**Comment by lodesmets** [comment]
Having the same problem on debian on ARM.

**Comment by iwalton3** [comment]
This should be resolved now. Please comment if this is still an issue.
