### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by shag00** [iwalton3/plex-mpv-shim#38]
I am unable to start with the following error:

`scott@scottubuntu:~$ plex-mpv-shim
2021-06-10 09:04:49,745 [ WARNING] root: Cannot load GUI. Falling back to command line interface.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/plex_mpv_shim/mpv_shim.py", line 39, in main
    from .gui_mgr import userInterface
  File "/usr/local/lib/python3.8/dist-packages/plex_mpv_shim/gui_mgr.py", line 1, in <module>
    from pystray import Icon, MenuItem, Menu
  File "/usr/local/lib/python3.8/dist-packages/pystray/__init__.py", line 48, in <module>
    Icon = backend().Icon
  File "/usr/local/lib/python3.8/dist-packages/pystray/__init__.py", line 40, in backend
    return importlib.import_module(__package__ + '._' + module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/pystray/_appindicator.py", line 22, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
2021-06-10 09:04:49,829 [    INFO] player: Using libmpv1 playback backend.
2021-06-10 09:04:49,844 [    INFO] root: Started GDM service
2021-06-10 09:04:49,844 [    INFO] client: Started HTTP server
^C
2021-06-10 09:05:19,172 [    INFO] root: Stopping services...
2021-06-10 09:05:19,173 [    INFO] client: Stopping HTTP server...`

Reference [https://github.com/iwalton3/plex-mpv-shim/issues/11](url) I have mpv ver 0.32.

**Comment by iwalton3** [comment]
Make sure you install the GUI dependencies if you want to GUI mode to work

**Comment by shag00** [comment]
Well of course, I have, 2 from memory, that is why this post, they were installed and I cannot get the GUI to appear.

**Comment by iwalton3** [comment]
Try installing gir1.2-appindicator3-0.1 or a similarly named package

**Comment by shag00** [comment]
Message changes for the better:
2021-08-03 12:19:04,424 [    INFO] conf: Loaded settings from json: /home/scott/.config/plex-mpv-shim/conf.json
2021-08-03 12:19:04,611 [    INFO] player: Using libmpv1 playback backend.
2021-08-03 12:19:04,627 [    INFO] root: Started GDM service
2021-08-03 12:19:04,627 [    INFO] client: Started HTTP server
2021-08-03 12:19:04,638 [   DEBUG] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
2021-08-03 12:19:04,638 [   DEBUG] PIL.PngImagePlugin: STREAM b'zTXt' 41 1315
2021-08-03 12:19:04,638 [   DEBUG] PIL.PngImagePlugin: STREAM b'bKGD' 1368 6
2021-08-03 12:19:04,638 [   DEBUG] PIL.PngImagePlugin: b'bKGD' 1368 6 (unknown)
2021-08-03 12:19:04,638 [   DEBUG] PIL.PngImagePlugin: STREAM b'pHYs' 1386 9
2021-08-03 12:19:04,638 [   DEBUG] PIL.PngImagePlugin: STREAM b'tIME' 1407 7
2021-08-03 12:19:04,638 [   DEBUG] PIL.PngImagePlugin: b'tIME' 1407 7 (unknown)
2021-08-03 12:19:04,638 [   DEBUG] PIL.PngImagePlugin: STREAM b'IDAT' 1426 612

Thank you.
