### ISSUE TITLE
[BUG] TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by Generator** [iwalton3/plex-mpv-shim#4]
On virtualenv
```
$ bin/plex-mpv-shim    
2019-08-19 23:51:56,563 [    INFO] Started GDM service
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aj/Desktop/plex-mpv-shim/lib/python3.7/site-packages/plex_mpv_shim/gdm.py", line 288, in run_discovery_loop
    self.discover()
  File "/home/aj/Desktop/plex-mpv-shim/lib/python3.7/site-packages/plex_mpv_shim/gdm.py", line 205, in discover
    self.__printDebug("Received data from %s" % server, 3)
TypeError: not all arguments converted during string formatting
```

**Comment by iwalton3** [comment]
That should be fixed now.
