### ISSUE TITLE
plex-mpv-shim not working

### ISSUE THREAD

**Issue by tarunjain3** [iwalton3/plex-mpv-shim#61]
error message :
**one running this command ; "plex-mpv-shim"** i got this under writter message

2022-01-24 23:28:46,757 [    INFO] conf: Loaded settings from json: /home/tarun/.config/plex-mpv-shim/conf.json
Traceback (most recent call last):
  File "/usr/local/bin/plex-mpv-shim", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/plex_mpv_shim/mpv_shim.py", line 47, in main
    from .player import playerManager
  File "/usr/local/lib/python3.6/dist-packages/plex_mpv_shim/player.py", line 23, in <module>
    import mpv
  File "/usr/local/lib/python3.6/dist-packages/mpv.py", line 531, in <module>
    _handle_func('mpv_detach_destroy',          [],                                         None, errcheck=None)
  File "/usr/local/lib/python3.6/dist-packages/mpv.py", line 478, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libmpv.so.2: undefined symbol: mpv_detach_destroy

**System configuration:**
ubuntu: 18.04
ram 8gb

Installing steps:
I followed all the steps mentioned in  [Documentation](https://github.com/Kagami/mpv.js/blob/master/README.md#get-libmpv)

- sudo pip3 install --upgrade plex-mpv-shim
- sudo pip3 install pystray
- sudo apt install python3-tk
- sudo pip3 install --upgrade python-mpv
- sudo apt install autoconf automake libtool libharfbuzz-dev libfreetype6-dev libfontconfig1-dev libx11-dev libxrandr-dev libvdpau-dev libva-dev mesa-common-dev libegl1-mesa-dev yasm libasound2-dev libpulse-dev libuchardet-dev zlib1g-dev libfribidi-dev git libgnutls28-dev libgl1-mesa-dev libsdl2-dev cmake wget python g++ libluajit-5.1-dev
- git clone https://github.com/mpv-player/mpv-build.git
- cd mpv-build
- echo --enable-libmpv-shared > mpv_options
./rebuild -j4
- sudo ./install
- sudo ldconfig

**Comment by iwalton3** [comment]
The latest MPV master branch has had breakage with the libmpv1 library. Use the last stable version or switch to external MPV mode, which should not be affected.

**Comment by iwalton3** [comment]
See here for another fix: https://github.com/iwalton3/plex-mpv-shim/issues/72#issuecomment-1365374854
