### ISSUE TITLE
Plex-MPV-Shim wont load on fresh install

### ISSUE THREAD

**Issue by Sure4Thing** [iwalton3/plex-mpv-shim#68]
Came across this project from a reddit post!  Followed the linux install instructions.  Installed libmpv1 package as well.  

From terminal I type plex-mpv-shim and I get errors

```
wil@notmicrosoft:~/Applications/mpv-build$ plex-mpv-shim 
2022-04-03 21:27:02,895 [    INFO] conf: Loaded settings from json: /home/wil/.config/plex-mpv-shim/conf.json
Traceback (most recent call last):
  File "/usr/local/bin/plex-mpv-shim", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/plex_mpv_shim/mpv_shim.py", line 47, in main
    from .player import playerManager
  File "/usr/local/lib/python3.8/dist-packages/plex_mpv_shim/player.py", line 23, in <module>
    import mpv
  File "/usr/local/lib/python3.8/dist-packages/mpv.py", line 531, in <module>
    _handle_func('mpv_detach_destroy',          [],                                         None, errcheck=None)
  File "/usr/local/lib/python3.8/dist-packages/mpv.py", line 478, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libmpv.so.2: undefined symbol: mpv_detach_destroy
```

Any help is appreciated!  I am running the latest Zorin OS system.

**Comment by iwalton3** [comment]
You are using a bleeding edge version of MPV that isn’t supported by the python-mpv library yet. Try enabling the mpv_ext config option or downgrade to an older MPV.

**Comment by Sure4Thing** [comment]
Yupp!  Enabling it was what was needed!  It now seems to start no problem!
