### ISSUE TITLE
"Name or service not known"

### ISSUE THREAD

**Issue by Arararararagi** [iwalton3/plex-mpv-shim#79]
- Fresh arch install
- Downloaded from releases
- Using python3.10
- Firefox 106.0.5 (with or without the userscript)
- Chrome 107.0.5304.110 (with or without the userscript)

Can't quite tell what I'm doing wrong. It was working until a few days ago. 

`[Arararararagi@Arararararagi plex-mpv-shim-1.10.3]$ python run.py 
2022-11-14 22:11:16,317 [    INFO] conf: Loaded settings from json: /home/Arararararagi/.config/plex-mpv-shim/conf.json
2022-11-14 22:11:16,430 [ WARNING] root: Cannot load GUI. Falling back to command line interface.
Traceback (most recent call last):
  File "/home/Arararararagi/.local/lib/python3.10/site-packages/pystray/_appindicator.py", line 23, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/mpv_shim.py", line 39, in main
    from .gui_mgr import userInterface
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/gui_mgr.py", line 1, in <module>
    from pystray import Icon, MenuItem, Menu
  File "/home/Arararararagi/.local/lib/python3.10/site-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/home/Arararararagi/.local/lib/python3.10/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/home/Arararararagi/.local/lib/python3.10/site-packages/pystray/__init__.py", line 28, in appindicator
    from . import _appindicator as backend; return backend
  File "/home/Arararararagi/.local/lib/python3.10/site-packages/pystray/_appindicator.py", line 26, in <module>
    gi.require_version('AyatanaAppIndicator3', '0.1')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available
2022-11-14 22:11:16,473 [    INFO] player: Using external mpv playback backend.
2022-11-14 22:11:16,473 [   DEBUG] mpv-jsonipc: Staring MPV from mpv.
2022-11-14 22:11:16,473 [   DEBUG] mpv-jsonipc: Using IPC socket /tmp/mpv62028527830667 for MPV.
2022-11-14 22:11:16,574 [   DEBUG] mpv-jsonipc: Found MPV socket.
2022-11-14 22:11:16,576 [   ERROR] menu: Could not load profile manager.
Traceback (most recent call last):
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/menu.py", line 63, in __init__
    profile_manager = VideoProfileManager(self, playerManager)
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/video_profile.py", line 24, in __init__
    self.load_shader_pack()
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/video_profile.py", line 36, in load_shader_pack
    raise FileNotFoundError("Could not find default shader pack.")
FileNotFoundError: Could not find default shader pack.
2022-11-14 22:11:16,588 [    INFO] root: Started GDM service
2022-11-14 22:11:16,589 [    INFO] client: Started HTTP server
2022-11-14 22:22:44,135 [   DEBUG] client: HttpHandler::handle_request request to '/player/timeline/poll?commandID=0&X-Plex-Product=Plex%20Web&X-Plex-Version=4.94.2&X-Plex-Client-Identifier=ufr8yes14tlqfvjv3tdasa3d&X-Plex-Platform=Firefox&X-Plex-Platform-Version=106.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=Linux&X-Plex-Device-Name=Firefox&X-Plex-Device-Screen-Resolution=2560x1273%2C2560x1440&X-Plex-Token=REDACTED&X-Plex-Language=en-GB&X-Plex-Target-Client-Identifier=78aa90f5-8d27-49e4-81f0-7d749658ea45'
2022-11-14 22:22:44,135 [   DEBUG] subscribers: RemoteSubscriberManager::addSubscriber added  [ufr8yes14tlqfvjv3tdasa3d]
2022-11-14 22:22:44,246 [   DEBUG] client: HttpHandler::handle_request request to '/player/timeline/poll?wait=1&commandID=0&X-Plex-Product=Plex%20Web&X-Plex-Version=4.94.2&X-Plex-Client-Identifier=ufr8yes14tlqfvjv3tdasa3d&X-Plex-Platform=Firefox&X-Plex-Platform-Version=106.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=Linux&X-Plex-Device-Name=Firefox&X-Plex-Device-Screen-Resolution=2560x1273%2C2560x1440&X-Plex-Token=REDACTED&X-Plex-Language=en-GB&X-Plex-Target-Client-Identifier=78aa90f5-8d27-49e4-81f0-7d749658ea45'
2022-11-14 22:22:44,246 [   DEBUG] subscribers: RemoteSubscriberManager::addSubscriber refreshed ufr8yes14tlqfvjv3tdasa3d
2022-11-14 22:22:44,246 [   DEBUG] subscribers: RemoteSubscriber::refresh ufr8yes14tlqfvjv3tdasa3d (cid=0)
2022-11-14 22:22:48,911 [   DEBUG] client: HttpHandler::handle_request request to '/player/playback/playMedia?type=video&providerIdentifier=com.plexapp.plugins.library&containerKey=%2FplayQueues%2F652%3Fown%3D1&key=%2Flibrary%2Fmetadata%2F33174&offset=0&machineIdentifier=5f19069add4c7676d71adbc506767f34110035b7&protocol=https&address=my-ip.plex.direct&port=32400&token=REDACTED&commandID=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.94.2&X-Plex-Client-Identifier=ufr8yes14tlqfvjv3tdasa3d&X-Plex-Platform=Firefox&X-Plex-Platform-Version=106.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=Linux&X-Plex-Device-Name=Firefox&X-Plex-Device-Screen-Resolution=2560x1273%2C2560x1440&X-Plex-Token=REDACTED&X-Plex-Language=en-GB&X-Plex-Target-Client-Identifier=78aa90f5-8d27-49e4-81f0-7d749658ea45'
2022-11-14 22:22:48,912 [   DEBUG] utils: get_plex_url Created URL: https://my-ip.plex.direct:32400/library/metadata/33174?includeMarkers=1&X-Plex-Token=REDACTED&X-Plex-Version=2.0&X-Plex-Client-Identifier=d971b610-1614-495d-8154-efa9abd4122f&X-Plex-Provides=player&X-Plex-Device-Name=Arararararagi-Arararararagi&X-Plex-Model=RaspberryPI&X-Plex-Device=RaspberryPI&X-Plex-Session-Identifier=83be646a-31d4-40c3-b011-48111c5c5fb6&X-Plex-Product=Plex+MPV+Shim&X-Plex-Platform=Plex+Home+Theater&X-Plex-Client-Profile-Name=Plex+Home+Theater
2022-11-14 22:22:48,946 [   DEBUG] utils: get_plex_url Created URL: https://my-ip.plex.direct:32400/playQueues/652?own=1&includeMarkers=1&X-Plex-Token=REDACTED&X-Plex-Version=2.0&X-Plex-Client-Identifier=d971b610-1614-495d-8154-efa9abd4122f&X-Plex-Provides=player&X-Plex-Device-Name=Arararararagi-Arararararagi&X-Plex-Model=RaspberryPI&X-Plex-Device=RaspberryPI&X-Plex-Session-Identifier=83be646a-31d4-40c3-b011-48111c5c5fb6&X-Plex-Product=Plex+MPV+Shim&X-Plex-Platform=Plex+Home+Theater&X-Plex-Client-Profile-Name=Plex+Home+Theater
2022-11-14 22:22:49,005 [   DEBUG] client: HttpHandler::playMedia /library/metadata/33174
2022-11-14 22:22:49,005 [   DEBUG] media: Video::select_best_media selected media 0
2022-11-14 22:22:49,005 [   DEBUG] media: Video::select_media selected media 0
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 36458)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/client.py", line 199, in do_GET
    self.handle_request("GET")
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/client.py", line 177, in handle_request
    getattr(self, handler)(path, query)
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/client.py", line 328, in playMedia
    playerManager.play(media_item, offset)
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/player.py", line 287, in play
    url = media_item.get_playback_url()
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/media.py", line 356, in get_playback_url
    direct_play = not self.is_transcode_suggested(video_bitrate, force_transcode, force_bitrate)
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/media.py", line 270, in is_transcode_suggested
    is_local = is_local_domain(self.parent.path.hostname)
  File "/home/Arararararagi/plex-mpv-shim-1.10.3/plex_mpv_shim/utils.py", line 141, in is_local_domain
    return ipaddress.ip_address(socket.gethostbyname(domain)).is_private
socket.gaierror: [Errno -2] Name or service not known
----------------------------------------
2022-11-14 22:22:49,006 [   DEBUG] client: HttpHandler::handle_request request to '/player/playback/playMedia?type=video&providerIdentifier=com.plexapp.plugins.library&containerKey=%2FplayQueues%2F652%3Fown%3D1&key=%2Flibrary%2Fmetadata%2F33174&offset=0&machineIdentifier=5f19069add4c7676d71adbc506767f34110035b7&protocol=https&address=my-ip.plex.direct&port=32400&token=REDACTED&commandID=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.94.2&X-Plex-Client-Identifier=ufr8yes14tlqfvjv3tdasa3d&X-Plex-Platform=Firefox&X-Plex-Platform-Version=106.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=Linux&X-Plex-Device-Name=Firefox&X-Plex-Device-Screen-Resolution=2560x1273%2C2560x1440&X-Plex-Token=REDACTED&X-Plex-Language=en-GB&X-Plex-Target-Client-Identifier=78aa90f5-8d27-49e4-81f0-7d749658ea45'
2022-11-14 22:22:49,006 [   DEBUG] utils: get_plex_url Created URL: https://my-ip.plex.direct:32400/library/metadata/33174?includeMarkers=1&X-Plex-Token=REDACTED&X-Plex-Version=2.0&X-Plex-Client-Identifier=d971b610-1614-495d-8154-efa9abd4122f&X-Plex-Provides=player&X-Plex-Device-Name=Arararararagi-Arararararagi&X-Plex-Model=RaspberryPI&X-Plex-Device=RaspberryPI&X-Plex-Session-Identifier=83be646a-31d4-40c3-b011-48111c5c5fb6&X-Plex-Product=Plex+MPV+Shim&X-Plex-Platform=Plex+Home+Theater&X-Plex-Client-Profile-Name=Plex+Home+Theater
2022-11-14 22:22:49,033 [   DEBUG] utils: get_plex_url Created URL: https://my-ip.plex.direct:32400/playQueues/652?own=1&includeMarkers=1&X-Plex-Token=REDACTED&X-Plex-Version=2.0&X-Plex-Client-Identifier=d971b610-1614-495d-8154-efa9abd4122f&X-Plex-Provides=player&X-Plex-Device-Name=Arararararagi-Arararararagi&X-Plex-Model=RaspberryPI&X-Plex-Device=RaspberryPI&X-Plex-Session-Identifier=83be646a-31d4-40c3-b011-48111c5c5fb6&X-Plex-Product=Plex+MPV+Shim&X-Plex-Platform=Plex+Home+Theater&X-Plex-Client-Profile-Name=Plex+Home+Theater
2022-11-14 22:22:49,092 [   DEBUG] client: HttpHandler::playMedia /library/metadata/33174
2022-11-14 22:22:49,092 [   DEBUG] media: Video::select_best_media selected media 0
2022-11-14 22:22:49,093 [   DEBUG] media: Video::select_media selected media 0
`

**Comment by LampPrinter** [comment]
Same issue. On some servers it is working.
On others I am getting "includeMarkers=1&X-Plex-Token=REDACTED" like the above poster.
Also 403 Forbidden error.

**Comment by imjuzcy** [comment]
> Also 403 Forbidden error.

Any chance you're using Cloudflare?
