### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by falstaff1288** [iwalton3/plex-mpv-shim#8]
Hello,

OS: Linux
Distribution: ArchLinux
Installation method: pip install --upgrade plex-mpv-shim; version 1.7.2
Plex client: Plex for Android 7.2.26.14578

Issue:

I am getting this error when I simply try to play a video on plex-mpv-shim:

```
Exception happened during processing of request from ('192.168.1.205', 37310)
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/lib/python3.8/site-packages/plex_mpv_shim/client.py", line 195, in do_GET
    self.handle_request("GET")
  File "/usr/lib/python3.8/site-packages/plex_mpv_shim/client.py", line 173, in handle_request
    getattr(self, handler)(path, query)
  File "/usr/lib/python3.8/site-packages/plex_mpv_shim/client.py", line 298, in playMedia
    media = Media(url, play_queue=playQueue)
  File "/usr/lib/python3.8/site-packages/plex_mpv_shim/media.py", line 448, in __init__
    XMLCollection.__init__(self, url)
  File "/usr/lib/python3.8/site-packages/plex_mpv_shim/media.py", line 437, in __init__
    self.tree       = et.parse(urllib.request.urlopen(get_plex_url(url)))
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```
Let me know if you need more details.

Cheers.

**Comment by iwalton3** [comment]
Is there a message similar to this prior:
```
2020-01-20 11:50:17,793 [   DEBUG] HttpHandler::handle_request request to '/player/playback/playMedia
```
I had friend have issues casting from Android to a Windows computer, so it may be the same issue.

**Comment by iwalton3** [comment]
Also, what is the get_plex_url log message between that and the error, if it is present?

**Comment by falstaff1288** [comment]
I got this. Not sure if it's the same.

```
2020-01-21 22:38:49,195 [   DEBUG] HttpHandler::handle_request request from 'Galaxy A70' to '/player/timeline/subscribe?protocol=http&port=32500&commandID=6&X-Plex-Token=REDACTED&includeExternalMedia=1'

```

For the second request: 
```
2020-01-21 22:38:54,561 [   DEBUG] get_plex_url Created URL: https://192-168-1-X.XXXXXXXXXXXXXXXXXXXXXXX.plex.direct:32400/library/metadata/56936?X-Plex-Token=REDACTED&X-Plex-Version=2.0&X-Plex-Client-Identifier=d614df14-d01c-4e19-abb8-33dd5ccc6e4c&X-Plex-Provides=player&X-Plex-Device-Name=XXX&X-Plex-Model=RaspberryPI&X-Plex-Device=RaspberryPI&X-Plex-Session-Identifier=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX&X-Plex-Product=Plex+MPV+Shim&X-Plex-Platform=Plex+Home+Theater&X-Plex-Client-Profile-Name=Plex+Home+Theater

```

**Comment by iwalton3** [comment]
Is there a `HttpHandler::handle_request` call that contains `/player/playback/playMedia`? That is the handler that is calling the error, so I'm suspecting that there is some inconsistency that I'm not expecting there.

**Comment by falstaff1288** [comment]
Oops, copied the wrong line earlier:

```
2020-01-21 22:38:54,559 [   DEBUG] HttpHandler::handle_request request from 'Galaxy A70' to '/player/playback/playMedia?protocol=https&providerIdentifier=com.plexapp.plugins.library&address=192-168-1-2.XXXXXXXXXXXXXXXXXXXXXXX.plex.direct&machineIdentifier=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&offset=86000&port=32400&containerKey=%2FplayQueues%2F13745%3Fown%3D1%26repeat%3D0%26window%3D200&type=video&commandID=7&key=%2Flibrary%2Fmetadata%2F56936&token=REDACTED&X-Plex-Token=REDACTED&includeExternalMedia=1'
```

**Comment by iwalton3** [comment]
That error seems to indicate the Plex URL for your server isn't resolving properly. It should not be related to the platform you are casting from. What happens when you run one of the following commands?

 - `dig 192-168-1-2.XXXXXXXXXXXXXXXXXXXXXXX.plex.direct`
 - `nslookup 192-168-1-2.XXXXXXXXXXXXXXXXXXXXXXX.plex.direct`
 - `ping 192-168-1-2.XXXXXXXXXXXXXXXXXXXXXXX.plex.direct`

Also, what happens if you change your DNS to 8.8.8.8?

**Comment by falstaff1288** [comment]
When I resolve the URL with dig using 8.8.8.8, I do get an answer:
```
$ dig @8.8.8.8 192-168-1-2..plex.direct +short
192.168.1.2
```
Changing the nameserver in my workstation to 8.8.8.8 doesn't seem to help tho. Getting the same error.

**Comment by iwalton3** [comment]
I suspect then that is a strange issue with urllib, since at least one other user was having this problem. Before I do anything like switch to requests, if you can run the following in a python interpreter, that would be helpful as I can't reproduce this locally:
With urllib (what is giving the error):
```
import urllib.request
urllib.request.urlopen("https://192-168-1-2.XXXXXXXXXXXXXXXXXXXXXXX.plex.direct:32400/web/index.html")
```
With requests:
```
import requests
requests.get("https://192-168-1-2.XXXXXXXXXXXXXXXXXXXXXXX.plex.direct:32400/web/index.html")
```
If the first one gives a similar error and the second one is successful, then that means there is a relatively easy fix for this issue.

**Comment by falstaff1288** [comment]
```
$ python --version
Python 3.8.1
```

**urllib**

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./urltest.py", line 8, in <module>
    urllib.request.urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**requests**
````
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f2cc0c9c790>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192-168-1-2.XXXXXXXXXXXXXXXXXXXXXXXX.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2cc0c9c790>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./urltest.py", line 12, in <module>
    requests.get(url)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192-168-1-2.XXXXXXXXXXXXXXXXXXXXXXXX.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2cc0c9c790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
````

**Comment by iwalton3** [comment]
So Python itself refuses to connect to your Plex server on your computer. DNS resolution on your computer is also fine, and I'm assuming the link you send Python opens just fine in a web browser. And I've had another user have this problem on Windows (you are on Arch Linux).

The specific python call that is failing is [getaddrinfo](https://docs.python.org/3/library/socket.html#socket.getaddrinfo), which both HTTP libraries are using:
```
import socket
socket.getaddrinfo("192-168-1-2.XXXXXXXXXXXXXXXXXXXXXXXX.plex.direct", 32400)
```

I'm assuming you don't have a local proxy server or anything else that could be unique about your network connection. I'm really not sure what is going on here.

**Comment by iwalton3** [comment]
What happens if you do the dig command without `@8.8.8.8` or referencing the DNS servers in `/etc/resolv.conf`? If you are using dnsmasq or dd-wrt provided DNS, the DNS rebinding prevention may be breaking the service. It still doesn't explain why it works elsewhere though. ([Article from Plex about this.](https://support.plex.tv/articles/206225077-how-to-use-secure-server-connections/))

**Comment by iwalton3** [comment]
Or if you really want to be adventurous, I figured out a way to monkey-patch getaddrinfo so that it is never called in the first place. Note that if the problem is DNS, the playback through MPV is still probably going to fail. (This was tested on Windows and Linux and prevents calls to that function.)

```
git clone https://github.com/iwalton3/plex-mpv-shim
git checkout fake-getaddrinfo
cd plex-mpv-shim
python3 run.py
```

**Comment by falstaff1288** [comment]
Sorry for not replying; life and all. 

I've just tried the tip regarding dnsmasq/DDWRT and it's working! Added the following line in the "Additional DNSMasq Options" section:

```
rebind-domain-ok=/plex.direct/
```

I'll close this issue. Thank you for your help!
