### ISSUE TITLE
Cannot install a working plex-mpv-shim

### ISSUE THREAD

**Issue by shag00** [iwalton3/plex-mpv-shim#82]
Ubuntu 22.10.
Per the instructions in the readme file, installing pystray and python3-tk are only required for the GUI and systray features, in other words optional. So just installing plex-mpv-shim gives this error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/mpv_shim.py", line 39, in main
    from .gui_mgr import userInterface
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/gui_mgr.py", line 1, in <module>
    from pystray import Icon, MenuItem, Menu
ModuleNotFoundError: No module named 'pystray'
`

So it seems they are not optional, so after installing pystray and python3-tk the following error pops up:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/mpv_shim.py", line 39, in main
    from .gui_mgr import userInterface
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/gui_mgr.py", line 1, in <module>
    from pystray import Icon, MenuItem, Menu
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 28, in appindicator
    from . import _appindicator as backend; return backend
  File "/usr/local/lib/python3.10/dist-packages/pystray/_appindicator.py", line 19, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
2023-01-08 19:44:02,373 [    INFO] player: Using libmpv1 playback backend.
Traceback (most recent call last):
  File "/usr/local/bin/plex-mpv-shim", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/mpv_shim.py", line 47, in main
    from .player import playerManager
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/player.py", line 568, in <module>
    playerManager = PlayerManager()
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/player.py", line 235, in __init__
    def handle_end_idle(event):
  File "/usr/local/lib/python3.10/dist-packages/mpv.py", line 1606, in register
    types = [MpvEventID.from_str(t) if isinstance(t, str) else t for t in event_types] or MpvEventID.ANY
  File "/usr/local/lib/python3.10/dist-packages/mpv.py", line 1606, in <listcomp>
    types = [MpvEventID.from_str(t) if isinstance(t, str) else t for t in event_types] or MpvEventID.ANY
  File "/usr/local/lib/python3.10/dist-packages/mpv.py", line 299, in from_str
    return getattr(kls, s.upper().replace('-', '_'))
AttributeError: type object 'MpvEventID' has no attribute 'IDLE'`

I had plex-mpv-shim up and running on an earlier version of ubuntu. I tried to install libappindicator3-dev but that is uninstallable. 

Any help appreciated.

**Comment by iwalton3** [comment]
Try the latest master version:

sudo pip3 install --upgrade git+https://github.com/iwalton3/plex-mpv-shim

I think I need to tag a release of this since this incompatible MPV version is starting to hit more distributions now.

**Comment by shag00** [comment]
Thanks for your reply. Installed your suggestion:
`Successfully built plex-mpv-shim
Installing collected packages: plex-mpv-shim
Successfully installed plex-mpv-shim-1.10.3`

One important issue cropped though, when installing either version a message appears, WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. This has occurred and rendered access to many programs impossible. Can plex-mpv-shim be made to work if installed in the home directory with no sudo installation?

Anyway the the new installation at least provides access to mpv from Plex but still has errors unlike my previous installation when started:
`2023-01-09 05:19:36,864 [    INFO] conf: Loaded settings from json: /home/scott/.config/plex-mpv-shim/conf.json
2023-01-09 05:19:36,872 [ WARNING] root: Cannot load GUI. Falling back to command line interface.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/mpv_shim.py", line 39, in main
    from .gui_mgr import userInterface
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/gui_mgr.py", line 1, in <module>
    from pystray import Icon, MenuItem, Menu
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/usr/local/lib/python3.10/dist-packages/pystray/__init__.py", line 28, in appindicator
    from . import _appindicator as backend; return backend
  File "/usr/local/lib/python3.10/dist-packages/pystray/_appindicator.py", line 19, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
2023-01-09 05:19:37,069 [    INFO] player: Using libmpv1 playback backend.
2023-01-09 05:19:37,076 [   ERROR] menu: Could not load profile manager.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/menu.py", line 63, in __init__
    profile_manager = VideoProfileManager(self, playerManager)
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/video_profile.py", line 24, in __init__
    self.load_shader_pack()
  File "/usr/local/lib/python3.10/dist-packages/plex_mpv_shim/video_profile.py", line 36, in load_shader_pack
    raise FileNotFoundError("Could not find default shader pack.")
FileNotFoundError: Could not find default shader pack.
2023-01-09 05:19:37,114 [    INFO] root: Started GDM service
2023-01-09 05:19:37,114 [    INFO] client: Started HTTP server`

**Comment by iwalton3** [comment]
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. This has occurred and rendered access to many programs impossible. Can plex-mpv-shim be made to work if installed in the home directory with no sudo installation?

It should also work using a user-level installation, but you may need to adjust your path. You can also run `run.py` from the cloned repository, assuming you install all of the dependencies.

**Comment by iwalton3** [comment]
The other two errors are non-fatal and are side effects of installing directly from the git repository.

**Comment by shag00** [comment]
The GUI dependencies are installed.

**Comment by iwalton3** [comment]
Try installing python3-gi

**Comment by shag00** [comment]
My package manager no longer works, let me try and fix it and install python3-gi.

**Comment by shag00** [comment]
python3-gi is/was already installed

**Comment by shag00** [comment]
Can pystray also be installed in the home directory? Seems it may be easier to reinstall the system and start again.

**Comment by shag00** [comment]
Could I also ask you to change your Linux installation instructions so that python sudo commands are not used. I have so much broken shit on my fresh install of Kubuntu 22.10 now it's a huge PitA.

**Comment by iwalton3** [comment]
`sudo pip3 uninstall pystray` will get rid of `pystray`.

`sudo pip3 uninstall pystray plex-mpv-shim python-mpv python-mpv-jsonipc certifi requests` should remove everything.

**Comment by shag00** [comment]
Got rid of everything and attempted a reboot but the system now only boots into emergency mode.

**Comment by shag00** [comment]
I have now re-installed Kubuntu 22.10 with Plex and plex-mpv-shim in my home directory and all works again. Just follow the linux install instructions but leave out the sudo in the 2 pythons installs. export PATH=$PATH:/home/scott/.local/bin needs to be added to my .bashrc file and that's it.

Please update your linux installation instructions to reflect the above as following them as is leads to a broken system that needs to be reinstalled, at least in Ubuntu 22.10. It's been a couple years since I looked at players for Plex and a fairly quick search after yesterday's drama solidifies my belief this program is the best way to watch my plex media.
