### ISSUE TITLE
External mpv does not work

### ISSUE THREAD

**Issue by AyyKamp** [iwalton3/plex-mpv-shim#9]
OS: Windows 
Version: 1.7.8 binary

I can't get an external version of mpv to work. It always fails with "Failed to execute script run" on startup. Here is my config: (I haven't changed anything aside from this.
```json
{
    "mpv_ext": true,
    "mpv_ext_ipc": null,
    "mpv_ext_path": "C:\\Users\\Ayyy\\AppData\\Roaming\\mpv\\mpv.exe",
    "mpv_ext_start": true,
}
```

**Comment by iwalton3** [comment]
Unfortunately pre-console error handling on Windows with the binary isn't great. I have prepared a console build, could you run this and tell me what the error is? https://iwalton.com/ushare/plex-mpv-shim_dbg.exe

If I had to guess I would say it is the MPV start timing out. Windows external MPV support can be a little intermittent, I probably need to increase the timeout.

**Comment by iwalton3** [comment]
There were two issues on Windows that could have been causing this:
 - MPV fails to start randomly. The implemented solution is retrying 3 times.
 - Older MPV versions do not allow command list support. A fix has been integrated.

Please test with this binary, and provide the output even if it works: https://iwalton.com/ushare/plex-mpv-shim_dbg2.exe

**Comment by AyyKamp** [comment]
I got the following
```
2020-02-19 20:41:40,843 [    INFO] Loaded settings from json: C:\Users\Ayyy\AppData\Roaming\plex-mpv-shim\conf.json
2020-02-19 20:41:40,965 [   DEBUG] Staring MPV from C:\Users\Ayyy\AppData\Roaming\mpv\mpv.exe.
2020-02-19 20:41:40,965 [   DEBUG] Using IPC socket \\.\pipe\mpv101194917198777 for MPV.
2020-02-19 20:41:41,069 [ WARNING] MPV start failed.
Traceback (most recent call last):
  File "site-packages\python_mpv_jsonipc.py", line 286, in __init__
  File "site-packages\python_mpv_jsonipc.py", line 166, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
2020-02-19 20:41:41,069 [   DEBUG] Staring MPV from C:\Users\Ayyy\AppData\Roaming\mpv\mpv.exe.
2020-02-19 20:41:41,069 [   DEBUG] Using IPC socket \\.\pipe\mpv101194917198777 for MPV.
2020-02-19 20:41:41,172 [ WARNING] MPV start failed.
Traceback (most recent call last):
  File "site-packages\python_mpv_jsonipc.py", line 286, in __init__
  File "site-packages\python_mpv_jsonipc.py", line 166, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
2020-02-19 20:41:41,172 [   DEBUG] Staring MPV from C:\Users\Ayyy\AppData\Roaming\mpv\mpv.exe.
2020-02-19 20:41:41,172 [   DEBUG] Using IPC socket \\.\pipe\mpv101194917198777 for MPV.
2020-02-19 20:41:41,275 [ WARNING] MPV start failed.
Traceback (most recent call last):
  File "site-packages\python_mpv_jsonipc.py", line 286, in __init__
  File "site-packages\python_mpv_jsonipc.py", line 166, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
Traceback (most recent call last):
  File "run.py", line 21, in <module>
  File "plex_mpv_shim\mpv_shim.py", line 47, in main
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\program files\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "plex_mpv_shim\player.py", line 477, in <module>
  File "plex_mpv_shim\player.py", line 69, in __init__
  File "site-packages\python_mpv_jsonipc.py", line 292, in __init__
python_mpv_jsonipc.MPVError: MPV process retry limit reached.
[26748] Failed to execute script run
```

**Comment by iwalton3** [comment]
Could you try it with this MPV build: https://mpv.srsfckn.biz/mpv-x86_64-20181002.7z

I was testing against that one, also what build are you using?

**Comment by AyyKamp** [comment]
I was using builds from [here](https://sourceforge.net/projects/mpv-player-windows/), but that didnt make a difference.

Using the "mysocket" solution worked with the second build but mpv was still kind of prone to crashes. Also you can only close mpv with task manager after closing plex-mpv-shim.

**Comment by iwalton3** [comment]
The "mysocket" was more of a test to try and figure out what the problem is, I don't consider that a valid fix.

The build from https://svwh.dl.sourceforge.net/project/mpv-player-windows/64bit/mpv-x86_64-20200216-git-e162bcb.7z worked for me. What this tells me though is that the problem is Python cannot launch the mpv.exe properly.

To help troubleshoot this more, could you [install python](https://www.python.org/downloads/windows/) and try to run this script?
```python3
import subprocess
subprocess.check_call(["C:\\Users\\Ayyy\\AppData\\Roaming\\mpv\\mpv.exe", "--input-ipc-server=testsocket", "--idle"])
```

**Comment by AyyKamp** [comment]
The script works

**Comment by iwalton3** [comment]
I think I just realized the problem. That script runs to completion and quits with MPV still open. On other platforms it blocks and that is currently relied on.

**Comment by iwalton3** [comment]
Could you try the two following scripts:

This one should hang and do nothing with no output, but I'm expecting it to crash for you.
```python3
import subprocess
subprocess.check_call(["C:\\Users\\Ayyy\\AppData\\Roaming\\mpv\\mpv.exe", '--input-default-bindings=yes', '--input-vo-keyboard=yes', '--input-media-keys=yes', '--include=C:\\Users\\Ayyy\\AppData\\Roaming\\plex-mpv-shim\\mpv.conf', '--player-operation-mode=cplayer', '--idle=yes', '--input-ipc-server=mpv105903133132681', '--input-terminal=no', '--terminal=no'])
```
And with the mpv.com that comes with the 7z build I linked. It should show some output or hopefully for you fail with an error message.
```python3
import subprocess
subprocess.check_call(["C:\\Users\\Ayyy\\AppData\\Roaming\\mpv\\mpv.com", '--input-default-bindings=yes', '--input-vo-keyboard=yes', '--input-media-keys=yes', '--idle=yes', '--input-ipc-server=mpv105903133132682', '-v'])
```
If neither of these fail, try opening another python window and tell me what happens when you run this:
```python3
import os.path
os.path.exists("\\\\.\\pipe\\mpv105903133132681") # For the first command.
os.path.exists("\\\\.\\pipe\\mpv105903133132682") # For the second command.
```

Apologies that troubleshooting this is a pain, but I haven't managed to reproduce the issue locally.

**Comment by AyyKamp** [comment]
The third script just printed True twice.

But I found something else:
After a fresh login the `dbg2.exe` actually works properly with this output:
```
2020-02-20 11:19:54,281 [    INFO] Loaded settings from json: C:\Users\Ayyy\AppData\Roaming\plex-mpv-shim\conf.json
2020-02-20 11:19:54,396 [   DEBUG] Staring MPV from C:\Users\Ayyy\Downloads\mpv.exe.
2020-02-20 11:19:54,396 [   DEBUG] Using IPC socket \\.\pipe\mpv27159533416760 for MPV.
2020-02-20 11:19:54,501 [ WARNING] MPV start failed.
Traceback (most recent call last):
  File "site-packages\python_mpv_jsonipc.py", line 286, in __init__
  File "site-packages\python_mpv_jsonipc.py", line 166, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
2020-02-20 11:19:54,501 [   DEBUG] Staring MPV from C:\Users\Ayyy\Downloads\mpv.exe.
2020-02-20 11:19:54,502 [   DEBUG] Using IPC socket \\.\pipe\mpv27159533416760 for MPV.
2020-02-20 11:19:55,762 [    INFO] Started GDM service
2020-02-20 11:19:55,762 [    INFO] Started HTTP server
2020-02-20 11:19:55,873 [   DEBUG] STREAM b'IHDR' 16 13
2020-02-20 11:19:55,873 [   DEBUG] STREAM b'zTXt' 41 1315
2020-02-20 11:19:55,874 [   DEBUG] STREAM b'bKGD' 1368 6
2020-02-20 11:19:55,874 [   DEBUG] b'bKGD' 1368 6 (unknown)
2020-02-20 11:19:55,874 [   DEBUG] STREAM b'pHYs' 1386 9
2020-02-20 11:19:55,874 [   DEBUG] STREAM b'tIME' 1407 7
2020-02-20 11:19:55,874 [   DEBUG] b'tIME' 1407 7 (unknown)
2020-02-20 11:19:55,874 [   DEBUG] STREAM b'IDAT' 1426 612
2020-02-20 11:19:55,876 [   DEBUG] Importing BlpImagePlugin
2020-02-20 11:19:55,876 [   DEBUG] Importing BmpImagePlugin
2020-02-20 11:19:55,877 [   DEBUG] Importing BufrStubImagePlugin
2020-02-20 11:19:55,877 [   DEBUG] Importing CurImagePlugin
2020-02-20 11:19:55,877 [   DEBUG] Importing DcxImagePlugin
2020-02-20 11:19:55,878 [   DEBUG] Importing DdsImagePlugin
2020-02-20 11:19:55,878 [   DEBUG] Importing EpsImagePlugin
2020-02-20 11:19:55,898 [   DEBUG] Importing FitsStubImagePlugin
2020-02-20 11:19:55,899 [   DEBUG] Importing FliImagePlugin
2020-02-20 11:19:55,899 [   DEBUG] Importing FpxImagePlugin
2020-02-20 11:19:55,900 [   DEBUG] Image: failed to import FpxImagePlugin: No module named 'olefile'
2020-02-20 11:19:55,900 [   DEBUG] Importing FtexImagePlugin
2020-02-20 11:19:55,900 [   DEBUG] Importing GbrImagePlugin
2020-02-20 11:19:55,901 [   DEBUG] Importing GifImagePlugin
2020-02-20 11:19:55,901 [   DEBUG] Importing GribStubImagePlugin
2020-02-20 11:19:55,901 [   DEBUG] Importing Hdf5StubImagePlugin
2020-02-20 11:19:55,902 [   DEBUG] Importing IcnsImagePlugin
2020-02-20 11:19:55,902 [   DEBUG] Importing IcoImagePlugin
2020-02-20 11:19:55,903 [   DEBUG] Importing ImImagePlugin
2020-02-20 11:19:55,904 [   DEBUG] Importing ImtImagePlugin
2020-02-20 11:19:55,904 [   DEBUG] Importing IptcImagePlugin
2020-02-20 11:19:55,904 [   DEBUG] Importing JpegImagePlugin
2020-02-20 11:19:55,905 [   DEBUG] Importing Jpeg2KImagePlugin
2020-02-20 11:19:55,905 [   DEBUG] Importing McIdasImagePlugin
2020-02-20 11:19:55,905 [   DEBUG] Importing MicImagePlugin
2020-02-20 11:19:55,906 [   DEBUG] Image: failed to import MicImagePlugin: No module named 'olefile'
2020-02-20 11:19:55,906 [   DEBUG] Importing MpegImagePlugin
2020-02-20 11:19:55,906 [   DEBUG] Importing MpoImagePlugin
2020-02-20 11:19:55,907 [   DEBUG] Importing MspImagePlugin
2020-02-20 11:19:55,907 [   DEBUG] Importing PalmImagePlugin
2020-02-20 11:19:55,908 [   DEBUG] Importing PcdImagePlugin
2020-02-20 11:19:55,909 [   DEBUG] Importing PcxImagePlugin
2020-02-20 11:19:55,909 [   DEBUG] Importing PdfImagePlugin
2020-02-20 11:19:55,915 [   DEBUG] Importing PixarImagePlugin
2020-02-20 11:19:55,915 [   DEBUG] Importing PngImagePlugin
2020-02-20 11:19:55,916 [   DEBUG] Importing PpmImagePlugin
2020-02-20 11:19:55,916 [   DEBUG] Importing PsdImagePlugin
2020-02-20 11:19:55,917 [   DEBUG] Importing SgiImagePlugin
2020-02-20 11:19:55,917 [   DEBUG] Importing SpiderImagePlugin
2020-02-20 11:19:55,918 [   DEBUG] Importing SunImagePlugin
2020-02-20 11:19:55,919 [   DEBUG] Importing TgaImagePlugin
2020-02-20 11:19:55,920 [   DEBUG] Importing TiffImagePlugin
2020-02-20 11:19:55,920 [   DEBUG] Importing WebPImagePlugin
2020-02-20 11:19:55,921 [   DEBUG] Importing WmfImagePlugin
2020-02-20 11:19:55,922 [   DEBUG] Importing XbmImagePlugin
2020-02-20 11:19:55,922 [   DEBUG] Importing XpmImagePlugin
2020-02-20 11:19:55,923 [   DEBUG] Importing XVThumbImagePlugin
```
But when I close the window and try it again it fails again:
```
2020-02-20 11:33:38,732 [    INFO] Loaded settings from json: C:\Users\Ayyy\AppData\Roaming\plex-mpv-shim\conf.json
2020-02-20 11:33:40,213 [   DEBUG] Staring MPV from C:\Users\Ayyy\Downloads\mpv.exe.
2020-02-20 11:33:40,214 [   DEBUG] Using IPC socket \\.\pipe\mpv105625145799371 for MPV.
2020-02-20 11:33:40,412 [ WARNING] MPV start failed.
Traceback (most recent call last):
  File "site-packages\python_mpv_jsonipc.py", line 286, in __init__
  File "site-packages\python_mpv_jsonipc.py", line 166, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
2020-02-20 11:33:40,412 [   DEBUG] Staring MPV from C:\Users\Ayyy\Downloads\mpv.exe.
2020-02-20 11:33:40,413 [   DEBUG] Using IPC socket \\.\pipe\mpv105625145799371 for MPV.
2020-02-20 11:33:40,615 [ WARNING] MPV start failed.
Traceback (most recent call last):
  File "site-packages\python_mpv_jsonipc.py", line 286, in __init__
  File "site-packages\python_mpv_jsonipc.py", line 166, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
2020-02-20 11:33:40,615 [   DEBUG] Staring MPV from C:\Users\Ayyy\Downloads\mpv.exe.
2020-02-20 11:33:40,615 [   DEBUG] Using IPC socket \\.\pipe\mpv105625145799371 for MPV.
2020-02-20 11:33:40,818 [ WARNING] MPV start failed.
Traceback (most recent call last):
  File "site-packages\python_mpv_jsonipc.py", line 286, in __init__
  File "site-packages\python_mpv_jsonipc.py", line 166, in __init__
python_mpv_jsonipc.MPVError: MPV not started.
Traceback (most recent call last):
  File "run.py", line 21, in <module>
  File "plex_mpv_shim\mpv_shim.py", line 47, in main
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\program files\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "plex_mpv_shim\player.py", line 477, in <module>
  File "plex_mpv_shim\player.py", line 69, in __init__
  File "site-packages\python_mpv_jsonipc.py", line 292, in __init__
python_mpv_jsonipc.MPVError: MPV process retry limit reached.
[11608] Failed to execute script run
```

**Comment by iwalton3** [comment]
This is maddening. Dbg2 was released with the most recent update.

It looks like this is an intermittent issue. Does running the two scripts repeatedly with different pipe names works? That is supposed to simulate exactly what is failing. The only way the error is supposed to happen (which is here: https://github.com/iwalton3/python-mpv-jsonipc/blob/master/python_mpv_jsonipc.py#L166) is only supposed to happen if MPV exits or MPV fails to create the named pipe.

Does it fail if you clone the git repository, install all of the dependencies (pip install python-mpv jellyfin-apiclient-python pywin32 pystray python-mpv-jsonipc), and double click the run.py.

You could also clone the python-mpv-jsonipc, change line 150 in the file I linked to “args = [mpv_location, ‘-v’]”, remove lines 153 and 154, install it by opening cmd in the folder as admin and running “pip install --upgrade .”, changing mpv.exe to mpv.com in your shim config, and the launching the shim until it fails.

Are you running any kind of antivirus that could be making this fail? I would get an issue like this rarely in testing (that is why it retries 3 times), but I have yet to figure out what causes it in testing.

Also, out of curiosity, what are you using external mpv for on Windows? Does the default not work properly?

**Comment by AyyKamp** [comment]
Hey its no biggie. My Windows installation probably just has some dumb quirk.
Thanks anyway for this project :)

**Comment by iwalton3** [comment]
This should be resolved in https://github.com/iwalton3/plex-mpv-shim/releases/tag/v1.7.13.
